version: '3.3'

services:
  node:
    image: node:8.9.4
    working_dir: "/app"
    environment:
      - COVERALLS_REPO_TOKEN
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules:cached
    tty: true
  docs:
    build: ./docker/mkdocs
    volumes:
      - ./:/app
    working_dir: /app
    tty: true