site_name: Bitnation Pangea Lib's
site_url: https://bitnation.co
repo_url: https://github.com/Bit-Nation/BITNATION-Pangea-libs
site_dir: docs_build
pages:
  - Home: index.md
  - Events: events.md
  - Schemata: schemata.md
  - Modules: modules.md
  - Interfaces: interfaces.md
theme: readthedocs
